from selenium.webdriver.common.by import By

class Edit_Profile_Selectors:
      
    uploadResourceButton = (By.XPATH,'//*[@title="Upload"]')
    resourceDetailsTxt = (By.XPATH,'//*[@class="modal-title h4"]')
    resourceDetailsModal  = (By.CLASS_NAME,'modal-body')
    cameraResourceButton = (By.XPATH,'//*[@title="Camara"]')
    audioResourceButton =(By.XPATH,'//*[@title="Audio"]')
    takePhotoButton = (By.XPATH,'//*[@title="Take photo"]')
    selectFileButton = (By.XPATH,'//*[@title="Take again"]')
    selectFileInput = (By.XPATH,'//*[@type="file"]')
    cloudButton = (By.CLASS_NAME,'upload-file-button')
    firstContinueButton = (By.XPATH,'//*[contains(@class,"rsw_3G")]/div[@class="stats-buttons"]/button[contains(@class,"button__ButtonText-sc-1tzab1-0")]')
    secondNumberButton = (By.CSS_SELECTOR,'div.nav > span:nth-child(2)')
    thirdNumberButton = (By.CSS_SELECTOR,'div.nav > span:nth-child(3)')
    fourthNumberButton = (By.CSS_SELECTOR,'div.nav > span:nth-child(4)')
    fifthNumberButton = (By.CSS_SELECTOR,'div.nav > span:nth-child(5)')
    sixthNumberButton = (By.CSS_SELECTOR,'div.nav > span:nth-child(6)')
    seventhNumberButton = (By.CSS_SELECTOR,'div.nav > span:nth-child(7)')
    eighthNumberButton = (By.CSS_SELECTOR,'div.nav > span:nth-child(8)')
    ninethNumberButton = (By.CSS_SELECTOR,'div.nav > span:nth-child(9)')
    sourceTypeModalCmb = (By.CSS_SELECTOR,'body > div.fade.modal.show > div > div > div.modal-body > div > div > div.rsw_2Y > div.rsw_2f.rsw_1z.rsw_1M.rsw_3G > div.step-container > div > div')
    sourceTypeModalInput = (By.CSS_SELECTOR,'#react-select-3-input')
    mediumModalCmb = (By.CSS_SELECTOR,'.rsw_1M > .step-container > .form-control')
    finishButton = (By.CSS_SELECTOR,'body > div.fade.modal.show > div > div > div.modal-body > div > div > div.rsw_2Y > div.rsw_2f.rsw_1z.rsw_1M.rsw_3G > div.stats-buttons > button.button__ButtonText-sc-1tzab1-0.button__DefaultButton-sc-1tzab1-1.jnpNuA')
    uploadButton = (By.ID,'left-tabs-example-tab-upload')
    resourceImageCard = (By.XPATH,'//*[contains(@class,"imagecard__ResourceContent-sc-1j3tso9-2")]')
    resourcePdfCard = (By.XPATH,'//*[contains(@class,"pdfcard__ResourceContent-sc-11ecl9g-2")]')
    resourceAudioCard = (By.XPATH,'//*[contains(@class,"audiocard__ResourceContent-sc-2why9p-2")]')
